name: publish_docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install --system \
            wheel \
            lxml \
            mkdocs-material \
            "cairosvg>=2.5" \
            "mkdocs-git-committers-plugin-2>=1.1.1" \
            "mkdocs-open-in-new-tab" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-git-authors-plugin" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-rss-plugin>=1.2" \
            "mkdocs-redirects>=1.0" \
            "markdown==3.7"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libfreetype6-dev

      - name: Deploy documentation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
