name: sync_playground
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["publish_docs"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - playground.html

jobs:
  deploy:
    if: github.actor == 'samapriya'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for GitHub Pages
        run: |
          # Wait for 1 minutes to allow GitHub Pages deployment to complete
          echo "Waiting for GitHub Pages deployment to complete..."
          sleep 60
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Download playground.html
        run: |
          curl -o playground.html https://raw.githubusercontent.com/samapriya/evap-docs/refs/heads/main/playground.html

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit files to gh-pages
        run: |
          git add playground.html
          git commit -m "Add playground.html from external source"

      - name: Push changes to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin gh-pages
